# Generated by Django 4.2.5 on 2023-10-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_cart_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
