# Generated by Django 4.2.5 on 2023-10-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='slug',
            field=models.SlugField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
