# Generated by Django 4.2.5 on 2023-10-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_checkout_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='slug',
        ),
        migrations.AddField(
            model_name='checkout',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
