# Generated by Django 4.2.5 on 2023-10-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_checkout_ship_checkout_shipaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='ship',
            field=models.BooleanField(default=True),
        ),
    ]
