# Generated by Django 4.2.5 on 2023-10-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_checkout_ship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='ship',
            field=models.BooleanField(default=False),
        ),
    ]
