# Generated by Django 4.2.5 on 2023-10-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_checkout_ship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='ship',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='shipAddress',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='shipEmail',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='shipcity',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='shipcountry',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='shipfirstname',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='shiplastname',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='shipphone',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='shipstate',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='shipzipcode',
        ),
    ]
