# Generated by Django 4.2.5 on 2023-10-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_checkout_ship_checkout_shipaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='ship',
        ),
    ]
